feature:
  - head-branch: ["feature"]

bug_fix:
  - head-branch: ["bug-fix"]

build:
  - head-branch: ["build"]

chore:
  - head-branch: ["chore"]

ci:
  - head-branch: ["ci"]

docs:
  - head-branch: ["docs"]

style:
  - head-branch: ["style"]

refactor:
  - head-branch: ["refactor"]

perf:
  - head-branch: ["perf"]

test:
  - head-branch: ["test"]

translation:
  - head-branch: ["translation"]

other:
  - head-branch: ["other"]
